import { cat } from "./servicesCategoryHelpers.js";

/** Часть 1 дерева «Услуги» (этап 1). */
export default [
  cat("Автосервис, аренда", "avtoservis-arenda", [
    cat("Автосервисы для автомобилей", "avtoservis-dlya-avtomobiley"),
    cat("Автосервисы для грузовиков и спецтехники", "avtoservis-gruzoviki-spectehnika"),
    cat("Автосервисы для другой техники", "avtoservis-drugaya-tehnika"),
    cat("Аренда авто", "arenda-avto"),
    cat("Аренда спецтехники", "arenda-spectehniki"),
  ]),
  cat("Перевозки и доставка", "perevozki-dostavka", [
    cat("По городу", "perevozki-po-gorodu"),
    cat("Между городами", "perevozki-mezhdu-gorodami"),
    cat("Международные", "perevozki-mezhdunarodnye"),
  ]),
  cat("Пассажирские перевозки", "passazhirskie-perevozki", [
    cat("Трансфер", "passazhir-transfer"),
    cat("Авто под заказ", "passazhir-avto-pod-zakaz"),
    cat("Другое", "passazhir-drugoe"),
  ]),
  cat("Грузчики, складские услуги", "gruzchiki-sklad", [
    cat("Грузчики", "gruzchiki-uslugi"),
    cat("Погрузка и разгрузка", "gruzchiki-pogruzka-razgruzka"),
    cat("Складские работы", "gruzchiki-skladskie-raboty"),
    cat("Фулфилмент", "fulfilment-uslugi"),
  ]),
  cat("Услуги эвакуатора", "evakuator", [
    cat("Эвакуация легковых авто", "evakuator-legkovye"),
    cat("Эвакуация грузовиков и спецтехники", "evakuator-gruzovye"),
    cat("Мото и малогабарит", "evakuator-moto"),
    cat("Подзаряд / техпомощь на дороге", "evakuator-tehpomoshch"),
  ]),
  cat("Ремонт и отделка", "remont-otdelka", [
    cat("Ремонт квартир и домов под ключ", "remont-kvartir-domov-pod-klyuch"),
    cat("Дизайн интерьеров", "dizayn-intererov"),
    cat("Сантехника", "santehnika"),
    cat("Электрика", "elektrika"),
    cat("Сборка и ремонт мебели", "sborka-remont-mebeli"),
    cat("Окна и балконы", "okna-balkony"),
    cat("Мастер на час", "master-na-chas"),
    cat("Вскрытие и ремонт замков", "vskrytie-remont-zamkov"),
    cat("Поклейка обоев и малярные работы", "oboi-malyarnye-raboty"),
    cat("Потолки", "potolki-remont"),
    cat("Полы и напольные покрытия", "poly-napolnye-pokrytiya"),
    cat("Штукатурные работы", "shtukaturnye-raboty"),
    cat("Двери", "dveri-remont"),
    cat("Плиточные работы", "plitochnye-raboty"),
    cat("Столярные и плотницкие работы", "stolyarnye-plotnickie"),
    cat("Гипсокартонные работы", "gipsokartonnye-raboty"),
    cat("Высотные работы", "vysotnye-raboty"),
    cat("Изоляция и утепление", "izolyatsiya-uteplenie"),
    cat("Ремонт коммерческих помещений", "remont-kommercheskih-pomescheniy"),
    cat("Вентиляция", "ventilyatsiya-remont"),
    cat("Другое", "remont-otdelka-drugoe"),
  ]),
  cat("Строительство", "stroitelstvo", [
    cat("Строительство домов под ключ", "stroitelstvo-domov-pod-klyuch"),
    cat("Строительство гаражей, бань, веранд", "stroitelstvo-garazhey-ban-verand"),
    cat("Отделка деревянных домов, бань, саун", "otdelka-derevyannyh-domov-ban-saun"),
    cat("Кладочные работы", "kladochnye-raboty"),
    cat("Кровельные работы", "krovelnye-raboty"),
    cat("Сварка, ковка, металлоконструкции", "svarka-kovka-metallokonstruktsii"),
    cat("Фундаментные и бетонные работы", "fundament-betonnye-raboty"),
    cat("Алмазное сверление и резка", "almaznoe-sverlenie-rezka"),
    cat("Снос и демонтаж", "snos-demontazh"),
    cat("Фасадные работы", "fasadnye-raboty"),
    cat("Проектирование и сметы", "proektirovanie-smety"),
    cat("Разнорабочие", "raznorabochie-stroyka"),
    cat("Изыскательные работы", "izyskatelnye-raboty"),
    cat("Лестницы", "lestnitsy-stroyka"),
    cat("Газификация", "gazifikatsiya"),
    cat("Коммерческое строительство", "kommercheskoe-stroitelstvo"),
    cat("Другое", "stroitelstvo-drugoe"),
  ]),
  cat("Сад, благоустройство", "sad-blagoustroystvo", [
    cat("Бурение, скважины, септики, колодцы", "burenie-skvazhiny-septiki"),
    cat("Водоёмы, бассейны, фонтаны", "vodoemy-basseyny-fontany"),
    cat("Дорожное строительство", "dorozhnoe-stroitelstvo"),
    cat("Ограждения, навесы, рольставни", "ograzhdeniya-navesy-rolstavni"),
    cat("Земляные работы", "zemlyanye-raboty"),
    cat("Озеленение, уход за садом и огородом", "ozelenenie-sad-ogorod"),
    cat("Другое", "sad-blagoustroystvo-drugoe"),
  ]),
  cat("Компьютерная помощь", "kompyuternaya-pomosh", [
    cat("Компьютеры", "kompyutery-pomosh"),
    cat("Принтеры", "printery-pomosh"),
    cat("Оборудование для майнинга", "majning-oborudovanie-pomosh"),
    cat("Игровые приставки", "igrovye-pristavki-pomosh"),
    cat("ОС и программы", "os-programmy-pomosh"),
    cat("Интернет и другие сети", "internet-seti-pomosh"),
  ]),
  cat("Красота", "krasota", [
    cat("Маникюр, педикюр", "beauty-manikyur-pedikyur"),
    cat("Услуги парикмахера", "beauty-parikmaherskie-uslugi"),
    cat("Ресницы, брови", "beauty-resnitsy-brovi"),
    cat("Перманентный макияж", "beauty-permanentnyy-makiyazh"),
    cat("Косметология", "beauty-kosmetologiya"),
    cat("Эпиляция", "beauty-epilyatsiya"),
    cat("Макияж", "beauty-makiyazh"),
    cat("СПА-услуги, массаж", "beauty-spa-massazh"),
    cat("Тату, пирсинг", "beauty-tatu-pirsing"),
    cat("Аренда рабочего места", "beauty-arenda-rabochego-mesta"),
    cat("Другое", "beauty-drugoe"),
  ]),
  cat("Здоровье", "zdorovie", [
    cat("Психология", "zdorovie-psihologiya"),
    cat("Диетология", "zdorovie-dietologiya"),
    cat("Фитнес, йога", "zdorovie-fitnes-yoga"),
    cat("Стоматология", "zdorovie-stomatologiya"),
    cat("Подология", "zdorovie-podologiya"),
    cat("Другое", "zdorovie-drugoe"),
  ]),
  cat("Ремонт и обслуживание техники", "remont-tehniki", [
    cat("Телевизоры", "remont-televizory"),
    cat("Мобильные устройства", "remont-mobilnye-ustroystva"),
    cat("Фото-, аудио-, видеотехника", "remont-foto-audio-video"),
    cat("Кондиционеры, вентиляция", "remont-konditsionery-ventilyatsiya"),
    cat("Стиральные, сушильные машины", "remont-stiralnye-sushilnye"),
    cat("Посудомоечные машины", "remont-posudomoechnye"),
    cat("Холодильники, морозильные камеры", "remont-holodilniki-morozilniki"),
    cat("Варочные панели, духовые шкафы", "remont-varochnye-duhovye"),
    cat("Газовые котлы, водонагреватели", "remont-kotly-vodonagrevateli"),
    cat("Кофемашины", "remont-kofemashiny"),
    cat("Швейные машины, оверлоки", "remont-shveynye-overloki"),
    cat("Другое", "remont-tehniki-drugoe"),
  ]),
  cat("Монтаж и установка техники", "montazh-ustanovka-tehniki", [
    cat("Телевизоры и кронштейны", "montazh-televizory"),
    cat("Кондиционеры и сплит-системы", "montazh-konditsionery"),
    cat("Кухонная техника", "montazh-kuhonnaya-tehnika"),
    cat("Стиральные и сушильные машины", "montazh-stiralnye"),
    cat("Водонагреватели и фильтры", "montazh-vodonagrevateli-filtry"),
    cat("Другое", "montazh-drugoe"),
  ]),
  cat("Оборудование, производство", "oborudovanie-proizvodstvo", [
    cat("Аренда оборудования", "arenda-oborudovaniya"),
    cat("Производство, обработка", "proizvodstvo-obrabotka"),
    cat("Ремонт промышленного оборудования", "oborudovanie-remont-promyshlennogo"),
    cat("Настройка и пусконаладка", "oborudovanie-puskonaladka"),
  ]),
];
