import { cat } from "./servicesCategoryHelpers.js";

/** Часть 2 дерева «Услуги». */
export default [
  cat("Обучение, курсы", "obuchenie-kursy", [
    cat("Предметы школы и вуза", "obuchenie-shkola-vuz"),
    cat("Иностранные языки", "obuchenie-inostrannye-yazyki"),
    cat("Детское развитие, логопеды", "obuchenie-detskoe-razvitie-logoped"),
    cat("Профессии и бизнес", "obuchenie-professii-biznes"),
    cat("Творчество, хобби, спорт", "obuchenie-tvorchestvo-hobby-sport"),
    cat("Вождение", "obuchenie-vozhdenie"),
    cat("Помощь в оформлении работ", "obuchenie-oformlenie-rabot"),
    cat("Духовные практики", "obuchenie-duhovnye-praktiki"),
    cat("Другое", "obuchenie-drugoe"),
  ]),
  cat("Деловые услуги", "delovye-uslugi", [
    cat("Бухгалтерия, финансы", "delovye-buhgalteriya-finansy"),
    cat("Консультирование", "delovye-konsultirovanie"),
    cat("Консультации по недвижимости", "delovye-konsultatsii-nedvizhimost"),
    cat("Юридические услуги", "delovye-yuridicheskie"),
    cat("IT, дизайн, тексты", "delovye-it-dizayn-teksty"),
    cat("Маркетинг и продвижение", "delovye-marketing-prodvizhenie"),
    cat("Переводы и легализация", "delovye-perevody-legalizatsiya"),
    cat("Подбор персонала", "delovye-podbor-personala"),
  ]),
  cat("Страхование", "strahovanie-uslugi", [
    cat("Авто и ОСАГО", "strahovanie-avto-osago"),
    cat("Имущество и жильё", "strahovanie-imuschestvo"),
    cat("Жизнь и здоровье", "strahovanie-zhizn-zdorove"),
    cat("Бизнес и ответственность", "strahovanie-biznes"),
    cat("Другое", "strahovanie-drugoe"),
  ]),
  cat("Услуги посредников", "uslugi-posrednikov", [
    cat("Услуги выкупа", "posredniki-vykup"),
    cat("Поставка товаров из-за границы", "posredniki-postavka-iz-granitsy"),
    cat("Помощь с финансовыми вопросами", "posredniki-finansy"),
    cat("Туристические услуги", "posredniki-turizm"),
    cat("Консультации", "posredniki-konsultatsii"),
  ]),
  cat("Полиграфия, наружная реклама", "poligrafiya-naruzhnaya-reklama", [
    cat("Визитки, листовки, буклеты", "poligrafiya-vizitki-listovki"),
    cat("Широкоформатная печать и баннеры", "poligrafiya-shirokoformat"),
    cat("Вывески и световые короба", "poligrafiya-vyveski"),
    cat("Сувенирная продукция", "poligrafiya-suveniry"),
    cat("Монтаж наружной рекламы", "poligrafiya-montazh-naruzhka"),
  ]),
  cat("Вывоз мусора и вторсырья", "vyvoz-musora", [
    cat("Вывоз мусора", "vyvoz-musora-usluga"),
    cat("Приём вторсырья", "priem-vtorsyrya"),
  ]),
  cat("Уборка", "uborka", [
    cat("Генеральная уборка", "uborka-generalnaya"),
    cat("Мойка окон", "uborka-moyka-okon"),
    cat("Простая уборка", "uborka-prostaya"),
    cat("Уборка после ремонта", "uborka-posle-remonta"),
    cat("Уборка офисов и коммерции", "uborka-ofisy-kommercheskaya"),
    cat("Чистка ковров", "uborka-chistka-kovrov"),
    cat("Чистка мягкой мебели", "uborka-chistka-mebeli"),
  ]),
  cat("Дезинфекция, дезинсекция, спецуборка", "dezinfektsiya-dezinsektsiya", [
    cat("Дезинфекция помещений", "dezinfektsiya-pomescheniya"),
    cat("Дезинсекция и дератизация", "dezinsektsiya-deratizatsiya"),
    cat("Уничтожение запахов и плесени", "dez-zapah-plesen"),
    cat("Уборка после ЧС и затоплений", "dez-uborka-posle-chs"),
  ]),
  cat("Бытовые услуги", "bytovye-uslugi", [
    cat("Изготовление ключей и заточка", "bytovye-klyuchi-zatochka"),
    cat("Пошив и ремонт одежды и других изделий", "bytovye-poshiv-odezhdy"),
    cat("Ремонт часов", "bytovye-remont-chasov"),
    cat("Химчистка, стирка", "bytovye-himchistka-stirka"),
    cat("Ювелирные услуги", "bytovye-yuvelirnye"),
  ]),
  cat("Праздники, мероприятия", "prazdniki-meropriyatiya", [
    cat("Организация и проведение мероприятий", "prazdniki-organizatsiya"),
    cat("Оформление и декор", "prazdniki-oformlenie-dekor"),
    cat("Прокат и аренда для мероприятий", "prazdniki-prokat-arenda"),
    cat("Организация досуга и отдыха", "prazdniki-dosug-otdyh"),
  ]),
  cat("Доставка продуктов, десертов, кейтеринг", "dostavka-produktov", [
    cat("Доставка готовой еды", "dostavka-gotovoy-edy"),
    cat("Торты и десерты на заказ", "dostavka-torty-deserty"),
    cat("Кейтеринг, официанты, повара, бармены", "dostavka-keytering-personal"),
  ]),
  cat("Фото- и видеосъёмка", "photo-video", [
    cat("Фотосъёмка", "photo-video-fotosyomka"),
    cat("Видеосъёмка", "photo-video-videosyomka"),
    cat("Аренда фотостудии", "photo-video-arenda-studii"),
  ]),
  cat("Няни, сиделки", "nyani-sidelki", [
    cat("Няни для детей", "nyani-deti"),
    cat("Сиделки и уход за пожилыми", "sidelki-pozhilye"),
    cat("Домработницы", "nyani-domrabotnitsy"),
    cat("Помощь в воспитании / репетиторство малышам", "nyani-vospitanie"),
  ]),
  cat("Уход за животными", "uhod-za-zhivotnymi", [
    cat("Выгул собак", "zhivotnye-vygul"),
    cat("Передержка и зоогостиницы", "zhivotnye-perederzhka"),
    cat("Груминг и стрижка", "zhivotnye-gruming"),
    cat("Кинолог / дрессировка", "zhivotnye-kinolog"),
    cat("Ветеринар на дом", "zhivotnye-vet-dom"),
  ]),
  cat("Искусство", "iskusstvo", [
    cat("Музыка, стихи, песни на заказ", "iskusstvo-muzyka-stihi"),
    cat("Услуги художников", "iskusstvo-hudozhniki"),
    cat("Кастомизация", "iskusstvo-kastomizatsiya"),
    cat("Рукоделие на заказ", "iskusstvo-rukodelie"),
  ]),
  cat("Охрана, безопасность", "ohrana-bezopasnost", [
    cat("Охрана объектов и сопровождение", "ohrana-obekty"),
    cat("Видеонаблюдение и СКУД", "ohrana-video-skud"),
    cat("Пожарная сигнализация", "ohrana-pozharnaya-signalizatsiya"),
    cat("Частные охранники / сопровождение", "ohrana-chastnaya"),
  ]),
  cat("Другое", "drugoe", [
    cat("Ремонт спортинвентаря", "drugoe-remont-sportinventarya"),
    cat("Ремонт музыкальных инструментов", "drugoe-remont-muzykalnyh"),
    cat("Ритуальные услуги", "drugoe-ritualnye"),
    cat("Ещё услуги", "drugoe-eshche-uslugi"),
  ]),
];
